### PR TITLE
add xlsx wordlist generator

### PR DESCRIPTION
**Pull request by RealFakeAccount**
I sometimes want to print out all the words on paper, so I modified the anki decks generator to generate xlsx file.

If you think this is redundant, feel free to close this pull request.

### CODE REVIEW

**Comment by SethClydesdale** [comment]
Hello @RealFakeAccount,

I think this would be a great addition! Can see it coming in handy for quickly referencing the vocab.

Just want to double check with you to see if everything is ready before merging, as I noticed the PR was originally marked as a draft.

**Comment by RealFakeAccount** [comment]
> 
> 
> Hello @RealFakeAccount,
> 
> I think this would be a great addition! Can see it coming in handy for quickly referencing the vocab.
> 
> Just want to double check with you to see if everything is ready before merging, as I noticed the PR was originally marked as a draft.

Hi @SethClydesdale :

Here is my plan for this PR :
 - modify README.md
 - update the bat file
 - generate word lists for 2nd Edition
 - (possibly) add a entry in the main page

Since I'm a little busy this week, I mark this PR as draft for now. 
I may have time to finished it this weekend.

BTW, thanks for your project. It helps me a lot.

**Comment by SethClydesdale** [comment]
Sounds good! For the main page entry, if you like, you can add it to the [news/info module](https://github.com/SethClydesdale/genki-study-resources/blob/bb0539681f5a108a2165307b5b7fe1c3251868d0/resources/javascript/homepage.js#L17) as a new message or onto an existing one.

> Since I'm a little busy this week, I mark this PR as draft for now.

That's fine. There's no rush, so whenever you're ready to merge, just let me know! 👍 

> BTW, thanks for your project. It helps me a lot.

You're welcome! Glad to hear it's of help to you. 😄

**Comment by RealFakeAccount** [comment]
@SethClydesdale I have finished. Please check it.

**Review by SethClydesdale — APPROVED** [review]
Hey, sorry about the delay; I was on vacation.

Everything looks good to merge! 👍 

Thank you for taking the time to work on this. I'm looking forward to using the lists that are generated from it.

**Pull request merged**
